### ISSUE TITLE
Requesting en-demo16 file for running example

### ISSUE THREAD

**Issue by arschoon** [ufal/whisper_streaming#1]
Where my I find the en-demo16.wav file used in the line from the documentation:
$ python3 whisper_online.py en-demo16.wav --language en --min-chunk-size 1 > out.txt

Thank you

**Comment by Gldkslfmsd** [comment]
Hello,
the file is just an example wav file with English speech. Do you need exactly this one? I didn't commit it because I suppose anybody can get an audio file easily. 

I think, but I'm not sure at this moment, that the audio format doesn't matter. If it does, it's sle 16k mono.

**Comment by Gldkslfmsd** [comment]
please reopen if you need

**Comment by arschoon** [comment]
Thank you!

Is there a way to use your program in real-time, so no audio file needed? I am looking for a solution to use whisper with my laptop microphone
