### ISSUE TITLE
Server and Client for Web App

### ISSUE THREAD

**Issue by marcinmatys** [ufal/whisper_streaming#100]
Do you have maybe some sample code for handling audio streaming for a web application
or maybe some instructions how to implement this ?

whisper_online_server.py is probably not suitable for processing audio chunks sended from browser like Firefox or Chrome.
Any sugestions which python (server side) and javascript (client side) library to use ?
Python: asyncio, websockets ?
Javascript: WebSocket and for web audio processing MediaRecorder or AudioContext or RecordRTC ?

Or maybe some others libraries or solution ?

**Comment by Gldkslfmsd** [comment]
hi, sorry, I don't have advice on SW engineering.
I hope that when you know how to make a TCP server-client, you can make it any other way you need.
