### ISSUE TITLE
How to start the command correctly：whisper_online_server.py

### ISSUE THREAD

**Issue by Micla-SHL** [ufal/whisper_streaming#101]
The first terminal run：`python3 whisper_online_server.py  --host 0.0.0.0   --port 8891  --warmup-file   2023专八听力考场版音频_16kHz.wav`
           output：
```
INFO	Loading Whisper large-v2 model for auto...
INFO	done. It took 3.59 seconds.
INFO	Whisper is warmed up.
INFO	Listening on('0.0.0.0', 8891)
INFO	Connected to client on ('127.0.0.1', 34710)
```
Another terminal run：`arecord -f S16_LE -c1 -r 16000 -t raw -D default | nc 192.168.0.244 8891`
output：
```
xcb_connection_has_error() 返回真
xcb_connection_has_error() 返回真
正在录音 原始資料 'stdin' : Signed 16 bit Little Endian, 频率16000Hz， Mono
```
How can I use my local browser's microphone to upload to the server for real-time transcription? 
I asked GPT4 and it prepared a web code intent to collect my microphone data and upload it to 192.168.0.244:8891. I'm wondering if I already have this job and it's superfluous

**Comment by Gldkslfmsd** [comment]
create a client for A TCP server
