### ISSUE TITLE
How to stream mic input on Windows?

### ISSUE THREAD

**Issue by abdullahkhalid00** [ufal/whisper_streaming#103]
I have been trying to implement real-time transcription by running the `whisper_online_server.py` file but I can't quite figure out how to stream audio via TCP/UDP. I was able to create a UDP connection via VLC but when I ran the python file, it gave me the following output:

Command I used:

`python3 whisper_online_server.py --host 127.0.0.1 --port 43001 --warmup-file audios/en.wav --min-chunk-size 1 --model tiny.en --task transcribe --lan en`

Output:

```
INFO    Loading Whisper tiny.en model for en...
INFO    done. It took 4.38 seconds.
INFO    Whisper is warmed up.
INFO    Listening on('127.0.0.1', 43001)
```

I can provide more detail on how I set up the UDP connection using VLC. Moreover, any guidance on using `ffmpeg` or `arecord` to do this would be much appreciated.

P.S. I apologize if the nature of this issue is amateurish, I am relatively new to these concepts.

**Comment by Gldkslfmsd** [comment]
hi, check some older closed issues. I think it's answered. 
 
There's netcat TCP client, I don't know the alternative on Win.

Reopen if you follow up.

Good luck!
