### ISSUE TITLE
Dealing with constant hallucinations

### ISSUE THREAD

**Issue by J-Korn** [ufal/whisper_streaming#121]
Using the large-v3 model to transcribe greek audio from a live stream, I am often met with continuous results writing "Υπότιτλοι AUTHORWAVE"

It seems the model is bugged in a way that outputs that phrase when it does not understand the input.

Setting vac and vad to True dos not seem to reduce that occurrence.

Is there some way I can discard this specific phrase or similar ones so they do not get confirmed and sent to the client?

**Comment by Gldkslfmsd** [comment]
hi, you can check whether it's the same with offline Whisper model with VAD on. 
If yes, then a better model can help, or make sure that the sound quality is good enough.

Alternatively, just remove that phrase from all transcripts before searching for the longest common prefix. But beware, it won't output it when you actually need it. And it may now work whenever Whisper hallucinates anything else.

**Comment by J-Korn** [comment]
This is not any actual greek phrase. My best guess is that the model was partially trained in greek using community generated subtitles for tv shows and whatnot, and they had the creator's name as an advertisement during moments of silence where actual captioning was not needed.
"Υπότιτλοι" translates to "Subtitles" and "AUTHORWAVE" is not a greek word, or any word that means anything for that matter.

This is using the large-v3 model and I cannot find any model that does greek better than this. Do note that this also shows up when transcribing videos with the base Whisper.

For now I am attempting to remove it like this:

 if self.contains_unwanted_word(tsw, "AUTHORWAVE"):
            logger.debug("Discarding transcription result due to unwanted word 'AUTHORWAVE'")
            return None, None, ""

Where I check the words retrieved from self.asr.ts_words(res) during process_iter and return early if this is found.
I am not sure this is the correct way to go about it though.

**Comment by J-Korn** [comment]
Any help on this matter would be greatly appreciated.

**Comment by Gldkslfmsd** [comment]
Hi, I'd like to help but I'm busy now. Small advice:
Create a "development set" -- an audio on which the hallucination happens, on which can you measure the ASR quality quickly -- preferrably by WER compared to gold transcript, or at least by counting the number of the hallucinated words. Measure the quality with your change/with various parameters and without. Use it for decision whether to apply the change or not.

Btw. -- latency measure should be applied as well but can be neglected for start.

**Comment by Gldkslfmsd** [comment]
Hi, @J-Korn , if I were you, I would remove the unwanted word from `tsw` after you create it with `tsw = self.asr.ts_words(res)` . Then process the rest of process_iter function as it was.

**Comment by J-Korn** [comment]
@Gldkslfmsd I have found that when this specific hallucination occurs, it always outputs either "AUTHORWAVE" or "Υπότιτλοι AUTHORWAVE" on its own, never alongside any actual relevant transcriptions that I would want to keep.
Going by this logic, I am attempting to discard the whole output by returning an empty tuple:
```
if self.contains_unwanted_word(tsw, "AUTHORWAVE"):
            logger.debug("Discarding transcription result due to unwanted word 'AUTHORWAVE'")
            return None, None, ""
```
Will this not work?

**Comment by Gldkslfmsd** [comment]
yes, if your observations are true than it makes sense
