### ISSUE TITLE
about a confused code comment "When it detects end of speech (non-voice for 500ms)"

### ISSUE THREAD

**Issue by lq0104** [ufal/whisper_streaming#125]
when I see the code whisper_online.py, I watch a line comment: https://github.com/ufal/whisper_streaming/blob/225f0383553a23f4ecc4c4751b73bc406a120c6c/whisper_online.py#L523
My question is: I cannot see any variable about the value of 500 in the MAIN branch. I just see it in the "vad-steaming" branch: https://github.com/ufal/whisper_streaming/blob/fdd3091d5980f58fd4c52ed3b6301507fdb6ca7f/voice_activity_controller.py#L8. So is there something missing in the code merge, or is there a misunderstanding on my part?

**Comment by Gldkslfmsd** [comment]
Thanks. It seems you are right. I thought it was 500ms but it seems to be 100ms: https://github.com/ufal/whisper_streaming/blob/225f0383553a23f4ecc4c4751b73bc406a120c6c/silero_vad.py#L13C18-L13C41 

So let's make it 500ms here: https://github.com/ufal/whisper_streaming/blob/225f0383553a23f4ecc4c4751b73bc406a120c6c/whisper_online.py#L538 and test whether it's doing what we expect.
