### ISSUE TITLE
opus-fast-mosestokenizer can't support windows,so this can't run on windows.

### ISSUE THREAD

**Issue by thunderlm** [ufal/whisper_streaming#13]
opus-fast-mosestokenizer can't support windows,so this can't run on windows.

**Comment by Gldkslfmsd** [comment]
OK, thanks for letting know. 
I can't help you with that. But I think that later I replace opus-fast-mosestokenizer by another sentence tokenizer that supports more languages.

**Comment by Gldkslfmsd** [comment]
btw., @thunderlm , can you please specify how did you realize that "opus-fast-mosestokenizer can't support windows"? Did you try pip install? What happened?

**Comment by Gldkslfmsd** [comment]
please, @thunderlm , let me know, otherwise I close this issue as not reproducible.
Thanks!
