### ISSUE TITLE
Issue with Whisper Online: AttributeError for openai-api Backend

### ISSUE THREAD

**Issue by chriswangzheyi** [ufal/whisper_streaming#132]
hi,

I’ve been working with the Whisper Online tool and encountered an issue while using the openai-api backend. I ran the following command:

`python whisper_online.py  bbc.wav  --backend openai-api > out.txt`

Unfortunately, I received the following error:

```
 raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'TranscriptionWord' object has no attribute 'get'
```

I’ve tried this multiple times with different audio formats (including WAV and MP3), but I keep encountering the same error.

Could you please help me understand what might be causing this issue and how I can resolve it?

Thanks in advance for your assistance.

**Comment by Gldkslfmsd** [comment]
hi, please check other open issues. It seems like OpenAI has changed the API in newer versions.
Investigations, fixes and PRs are needed.

Otherwise we can declare that OpenAI API is not maintained anymore.

**Comment by Gldkslfmsd** [comment]
duplicated: #94
