### ISSUE TITLE
Error in VAC

### ISSUE THREAD

**Issue by MohammedShokr** [ufal/whisper_streaming#136]
I am trying to use `--vac` option in real time transcription but I am getting `builtins.ValueError: Provided number of samples is 641 (Supported values: 256 for 8000 sample rate, 512 for 16000)` error.
How to solve that?

**Comment by Gldkslfmsd** [comment]
it should be reported to faster-whisper, or to the orig whisper.

Or apply the fix in PR #115

**Comment by MohammedShokr** [comment]
Ok, thank you :pray:
