### ISSUE TITLE
use --vac error : builtins.ValueError: Provided number of samples is 20805 (Supported values: 256 for 8000 sample rate, 512 for 16000)

### ISSUE THREAD

**Issue by evolost** [ufal/whisper_streaming#141]
I have used the latest code and found that I cannot normally import `FixedVADIterator` using `from silero_vad import FixedVADIterator`. So, I made a copy named `my_silero_vad.py` and modified the import to `from my_silero_vad import FixedVADIterator`, which successfully imported it. However, I encountered the following error at the end:
```
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/vad/model/vad_annotator.py", line 26, in forward
    if _2:
      _3 = torch.format(_0, (torch.size(x0))[-1])
      ops.prim.RaiseException(_3, "builtins.ValueError")
      ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    else:
      pass

Traceback of TorchScript, original code (most recent call last):
  File "/home/keras/notebook/nvme1/adamnsandle/silero-models-research/vad/model/vad_annotator.py", line 480, in forward
        num_samples = 512 if sr == 16000 else 256
        if x.shape[-1] != num_samples:
            raise ValueError(f"Provided number of samples is {x.shape[-1]} (Supported values: 256 for 8000 sample rate, 512 for 16000)")
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

        batch_size = x.shape[0]
builtins.ValueError: Provided number of samples is 20805 (Supported values: 256 for 8000 sample rate, 512 for 16000)
```

**Comment by Gldkslfmsd** [comment]
>  I cannot normally import FixedVADIterator using from silero_vad import FixedVADIterator

Why?

> `builtins.ValueError: Provided number of samples is 20805 (Supported values: 256 for 8000 sample rate, 512 for 16000)`

if VADIterator doesn't work with any length of input? it should be reported to silero. They changed interface of their v5 model but they haven't updated VADIterator. FixedVADIterator is my suboptimal hotfix

**Comment by evolost** [comment]
Thank you, I'll look into it.在 2024年11月25日，21:07，Dominik Macháček ***@***.***> 写道：﻿

I cannot normally import FixedVADIterator using from silero_vad import FixedVADIterator

Why?

builtins.ValueError: Provided number of samples is 20805 (Supported values: 256 for 8000 sample rate, 512 for 16000)

if VADIterator doesn't work with any length of input? it should be reported to silero. They changed interface of their v5 model but they haven't updated VADIterator. FixedVADIterator is my suboptimal hotfix

**Comment by Gldkslfmsd** [comment]
https://github.com/snakers4/silero-vad/issues/582 -- we need to fix it by ourselves
