### ISSUE TITLE
windows opus-fast-mosestokenizer installation

### ISSUE THREAD

**Issue by tatarmb4s** [ufal/whisper_streaming#20]
Hello! When I try to run the whisper_online_server I get this error: 

Exception has occurred: FileNotFoundError
[WinError 2] The system cannot find the file specified
  File "S:\AI\Testing\HuggingFace\openai\whisper_streaming\whisper_online.py", line 436, in create_tokenizer
    return MosesTokenizer(lan)
           ^^^^^^^^^^^^^^^^^^^
  File "S:\AI\Testing\HuggingFace\openai\whisper_streaming\whisper_online_server.py", line 64, in <module>
    online = OnlineASRProcessor(asr,create_tokenizer(tgt_language))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Everything is the default, I just cloned the repo and installed all dependencies. How can I solve this?

I'm on Windows, using py3.11.3 in a .venv. 
![image](https://github.com/ufal/whisper_streaming/assets/94311853/ef98a9b6-b8cf-40a7-97a3-9ff08b7045a6)

**Comment by tatarmb4s** [comment]
I found a temporary solve, in here:
https://stackoverflow.com/questions/55871850/mosestokenizer-issue-winerror-2-the-system-cannot-find-the-file-specified#:~:text=use%20sacremoses%20instead%20of%20moses.%20pip%20install%20-U,%27my%27%2C%20%27name%27%2C%20%27is%27%2C%20%27artem%27%5D%29%29%20for%20complete%20details%20sacremoses

**Comment by Gldkslfmsd** [comment]
> installed all dependencies

Are you sure that you installed opus-fast-mosestokenizer correctly?

And can you confirm that it works well with `pip install sacremoses` on Windows? No changes in code are needed?

**Comment by umaryasin33** [comment]
Do you have ffmpeg installed on your system?

# on Ubuntu or Debian
sudo apt update && sudo apt install ffmpeg

# on Arch Linux
sudo pacman -S ffmpeg

# on MacOS using Homebrew (https://brew.sh/)
brew install ffmpeg

# on Windows using Chocolatey (https://chocolatey.org/)
choco install ffmpeg

# on Windows using Scoop (https://scoop.sh/)
scoop install ffmpeg

**Comment by white1-doggy** [comment]
but it doesn't for mosestokenizer in sacremoses
![Uploading 截屏2023-12-08 14.18.58.png…]()

**Comment by Gldkslfmsd** [comment]
yes, sacremoses does not have sentence segmentation

**Comment by white1-doggy** [comment]
> yes, sacremoses does not have sentence segmentation

so, please tell me how can I slove this question?

**Comment by Gldkslfmsd** [comment]
resolved -- same reason as #23
