### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by lucasjinreal** [ufal/whisper_streaming#22]
the  opus-fast-mosestokenizer seems not able build on macOS.

 any help?

**Comment by Gldkslfmsd** [comment]
https://github.com/ufal/whisper_streaming/issues/20 ?
How about sacremoses?

**Comment by lucasjinreal** [comment]
@Gldkslfmsd  hi, run it:  pip install pip install sacremoses

still:

   from mosestokenizer import MosesTokenizer
ModuleNotFoundError: No module named 'mosestokenizer'

**Comment by Gldkslfmsd** [comment]
OK. Then I'm sorry, I can't help with MacOS support, I don't have access to MacOS. 

But generally, you can replace the tokenizer with another one that works. There are more implementations of mosestokenizer. I hope that one of them works, although not as fast as fast-mosestokenizer.

**Comment by Gldkslfmsd** [comment]
And are you sure that it doesn't work on MacOS? Isn't it because your python version?

https://github.com/mingruimingrui/fast-mosestokenizer/pull/4

**Comment by jelmervdl** [comment]
@lucasjinreal which version on macOS and Python (and pip) are you using?

I.e. what do these commands give you?
```bash
sw_vers
python3 --version
pip --version
```

(Asking for pip specifically because with brew you can have a weird situation where `pip` doesn't use the `python3` in your path, but the one shipped with macOS)

**Comment by lucasjinreal** [comment]
@Gldkslfmsd  unfortunately, I tested jetmervdl's fork, it doesn't able to build on macOS, many of its dependencies depends on tar.gz file, some of them can not build on macOS at all. Beside, this is a really a bad practically to include you dependencies as tar.gz (this is not a problem. but when glibc goes as tar.gz would cause many fundamental issue).

I still need help, none of opus-fastxxx got work on macOS actually.

**Comment by Gldkslfmsd** [comment]
@lucasjinreal how about installing from wheel, not from `pip install opus-fast-mosestokenizer`? It means download the .whl file from [Jelmer's link,](https://pypi.org/project/opus-fast-mosestokenizer/#files) and then follow this: https://www.educative.io/answers/how-to-install-a-python-package-with-a-whl-file

**Comment by lucasjinreal** [comment]
@Gldkslfmsd  thanks for the info. But unfortunately am using M1 Mac book Pro. It doesn't provides such one wheel.

However, I am very wondering how does it alble to build it....  The opus-fast-mosestokenizer and fast-mosestokenizer code really like a mess to me. 

Does there any more build friendly alternative lib to them? Actually, both opus-fast-mosestokenizer and fast-mosestokenizer seems not maintained any longer, opus-fast-mosestokenizer even just a fork with out issue feedback. Using them have very huge risk

**Comment by jelmervdl** [comment]
Aah, arm, yes, I hadn't thought of that. Unfortunately there are no wheels for m1 yet. Those should definitely be added. 

From what I understand, the plugin prefers to compile its own dependencies during build as opposed to using the shared libraries because often those don't allow static linking, which it needs for wheels.

The opus-fast-mosestokenizer repo is just a fork with the goal of fixing the installation issues encountered by the OPUS project and HPLT partners that uses them. I tried to get wheels built upstream, but the original fast-mosestokenizer repo seems to be unmaintained at the moment.

If you don't really need the speed, I'd say stick with something like sacremoses, which is better maintained and doesn't have all the dependencies.

**Comment by Gldkslfmsd** [comment]
OK. But we need sentence segmentation in this repo, and I'm afraid that sacremoses doesn't have it. Do you know another option, @jelmervdl ?

Speed is the first priority in this repo, second priority is having it working.

**Comment by jelmervdl** [comment]
Yes, that's fair. I mainly use other tools, not python libraries, for that, so no I don't really have an off-the-shelf alternative for you.

I'll have a look at whether I can make the setup.py behave more like a proper package that will download and install dependencies when not a wheel. If that's working, I'll also see whether I can switch this repo to cibuildwheels action which can do cross-compilation to make ARM wheels on Github Actions.

**Comment by lucasjinreal** [comment]
@Gldkslfmsd  I can installed it: `Successfully installed mosestokenizer-1.2.1 openfile-0.0.7 toolwrapper-2.1.0 uctools-1.3.0`
Not sure can be called correctly or not. Have a fallback without building c++ libs is a good choice.

@jelmervdl  Really appreciated if a setup.py which works for most distribution can be added. It useful turns of resolving building issues of opus-xxx libs. For me, the fast-xxx are really out-dated, but opus-xxx hard to build it doesn't support c++14 but google's absil needs it.

**Comment by vincentwi** [comment]
Hi, Mac M2 user here, following the thread. 

Confirming mosestokenizer builds on arm wheels, and can thereafter be called: https://pastebin.com/YrTNA0jc

Similarly, sacremoses builds as well, but as @Gldkslfmsd mentioned earlier, it doesn't do sentence segmentation.  

Also confirming opus-fast-mosestokenizer does not build for mac-arm. Full log here: https://pastebin.com/a10cW1jF

fast-mosestokenizer doesnt work either, but you seem to have already caught that: https://github.com/mingruimingrui/fast-mosestokenizer/issues/5

`ProductName:		macOS
ProductVersion:		13.6
BuildVersion:		22G120
Python 3.10.13
pip 23.3 `

**Comment by lucasjinreal** [comment]
@Gldkslfmsd  any examples to follow?

**Comment by Gldkslfmsd** [comment]
@lucasjinreal -- at this moment, you can use this fork: https://github.com/ufal/whisper_streaming/pull/23
I can not merge this in this version because it breaks working for Unix, but for you it should work, suboptimally, very slowly.

**Comment by Gldkslfmsd** [comment]
closing -- same reason as #23

**Comment by kgrusha** [comment]
Here's the solution so people can find it while the pull request to **opus-fast-mosestokenizer** is pending:

- https://github.com/Helsinki-NLP/opus-fast-mosestokenizer/pull/4
- https://github.com/mingruimingrui/fast-mosestokenizer/issues/5

**Comment by jonigl** [comment]
Hey everyone! I’ve created a fork to address the issues with running the project on Apple Silicon-based machines: https://github.com/jonigl/whisper_streaming_apple_silicon_fix

I simply added the suggestions shared here to make it easier to run on M1/M2/etc Macs . I’ve also updated the `README.md` with step-by-step instructions to make testing super simple on MacOS.

Hopefully, this helps anyone who's had trouble getting it to work! Feel free to check it out and let me know if you have any feedback
