### ISSUE TITLE
Running whisper_streaming with a fine-tuned whisper model

### ISSUE THREAD

**Issue by yilmazay74** [ufal/whisper_streaming#27]
Hi Everyone,
I want to use whisper_streaming with my custom fine-tuned whisper model.
However, as far as I see from the command line parameters, it only accepts whisper's pretrained models, tiny, base, small, medium and large. Is it possible to make it work with a fine-tuned model ?

**Comment by Gldkslfmsd** [comment]
yes. Option


  --model_dir MODEL_DIR
                        Dir where Whisper model.bin and other files are saved. This option overrides --model and --model_cache_dir parameter.

**Comment by yilmazay74** [comment]
it looks like model_dir parameter hasn't been implemented yet.
on the 58'th line ofthe whisper_online.py it says this:
    _def load_model(self, modelsize=None, cache_dir=None, model_dir=None):
        if model_dir is not None:
            print("ignoring model_dir, not implemented",file=sys.stderr)
        return whisper.load_model(modelsize, download_root=cache_dir)_

![Uploading image.png…]()

**Comment by yilmazay74** [comment]
May I ask whether there will be any solution for this issue in the near future?

**Comment by Gldkslfmsd** [comment]
It's implemented in FasterWhisperASR, but not in WhisperTimestampedASR. I recommend using  FasterWhisperASR with faster-whisper backend because it is much faster.

Do you really need whisper_timestamped backend? E.g. due to installation requirements? If yes, then you can implement and test the option that passes model_dir correctly. I'm busy now, I'm not planning it.

**Comment by yilmazay74** [comment]
Well, since I am working on CPU, I thought I need to use whisper_timestamped backend. 
Actually with some tweaks on the code, I made it work on whisper_timestamped as well. 
However, the accuracy results are not so satisfying. 
When we test our finetuned model with normal whisper, our finetuned model performs a lot better than the base whisper model.
So, we were expecting same better results on whisper_streaming as well.
I will try faster_whisper and see if it makes any difference on the accuracy.
Thanks anyway for guidance.

**Comment by yilmazay74** [comment]
Thanks a lot for your advice, that is definetly very useful. 
Althoug, I made it work With whisper_timestamped mode,  it is not very promising. 
However, I also am going to try with longer chunk sizes as you suggested.
But mainly I want to focus on faster-whisper since it is designed to work with finetuned models.
Regarding faster-whisper mode, it works with pretrained whisper base model.
Unfortunately I could not make faster-whisper work with my own fine-tuned model. It is giving the following errors:
  _File "E:\SpeechTeam\Whispers\whisper_streaming\venv2\lib\site-packages\faster_whisper\transcribe.py", line 128, in __init__
    self.model = ctranslate2.models.Whisper(
RuntimeError: Unsupported model binary version. This executable supports models with binary version v6 or below, but the model has binary version v67324752. This usually means that the model was generated by a later version of CTranslate2. (Forward compatibility is not guaranteed.)_
It looks like, faster-whisper is somehow bounded with older versions of some dependencies.
I will very much appreciate it if you can give me some ideas about what I can do to overcome this problem.
Thanks in advance.

**Comment by Gldkslfmsd** [comment]
hi, I have no idea what versions of models faster-whisper needs. Maybe try if your model works with faster-whisper offline mode implementation. And if not, consult faster-whisper authors.
