### ISSUE TITLE
How did you measure computationally unaware latency?

### ISSUE THREAD

**Issue by lifefeel** [ufal/whisper_streaming#32]
This question is not about code issue.

I read your paper and would like to know more specifically about computationally unaware latency.

In your code, computationally unaware mode does not measure latency. How did you measure latency?

I want to reproduce your result.

Thanks.

**Comment by Gldkslfmsd** [comment]
I have another code for it. It's described in the paper -- WER align words in hypothesis and gold transcript, and then make diff of their timestamps. 
Do you need the code? I think I can publish it.

**Comment by lifefeel** [comment]
Yes. It's very helpful to reproduce the same result.

**Comment by Gldkslfmsd** [comment]
ok

**Comment by Gldkslfmsd** [comment]
please reopen if you have question or issue
