### ISSUE TITLE
whisper_online.py returns only 'Python'

### ISSUE THREAD

**Issue by BBIBIBBIBI** [ufal/whisper_streaming#35]
```
(streaming) C:\Users\user>python3 whisper_online.py en-demo16.wav --language en --min-chunk-size 1 > out.txt
Python
```

```
(streaming) C:\Users\user>python3 whisper_online.py 3-1.wav --model large-v2
Python
```

```
(streaming) C:\Users\user\Documents\Python>python3 whisper_online.py 3-1.wav --model large-v2
Python
```

I installed and ran the streaming whisperer according to the manual. 
(I replaced the opus-fast-tokenizer with the scremoses)
However, there is no error and only repeats just 'Python' like that.

I am using Windows 10, Anaconda and Python 3.8.0.
What's wrong with me...

**Comment by Gldkslfmsd** [comment]
I don't know. You can try to put some debug prints and check if you see them.

Btw., I'm not sure if sacremoses has sentence segmentation. If not, then you can not use it.
