### ISSUE TITLE
Keep recieving transcription text from the server even after I mute my mic/stop transmitting

### ISSUE THREAD

**Issue by umaryasin33** [ufal/whisper_streaming#37]
I am using  python3 whisper_online_server.py  --model large  --min-chunk-size 3 <server> <port>

This is a screenshot from the client-side:

![Screenshot 2023-11-30 160153](https://github.com/ufal/whisper_streaming/assets/39225051/95915fea-afbd-4305-a013-46ff4e6009df)

I tried with different min-chunk-sizes and models but this keeps happening.
Any idea on how to resolve this.

**Comment by Gldkslfmsd** [comment]
Hi, 
what's the problem? Can you elaborate? Is your problem reproducible? Can you give more info so we can reproduce it?

Maybe you're not using VAD filter and you're transcribing silence, which produces "is." many times?

**Comment by umaryasin33** [comment]
Thank you I wasn't using vad filter as pointed out.
