### ISSUE TITLE
Custom HuggingFace tokenizer with faster-whisper

### ISSUE THREAD

**Issue by kenaii** [ufal/whisper_streaming#38]
How can I use my own trained tokenizer?

**Comment by Gldkslfmsd** [comment]
tokenizer for sentence segmentation, right?

1) wrap it in an object that has split function that works like the one of MosesTokenizer
2) pass it to OnlineASRProcessor

**Comment by kenaii** [comment]
Thank you for your fast response.

Actually no, My question means, how can I use the Hugging Face formatted tokenizer? 

I have a Hugging Face formatted tokenizer with files such as vocab.json, vocabulary.json, added_tokens.json, normalizer.json, special_tokens_map.json, and merges.txt inside, along with my ct2 translated whisper model. However, Faster-whisper only takes a tokenizer.json file. How can I use my Hugging Face formatted tokenizer? Is it possible to convert it to tokenizer.json?

**Comment by kenaii** [comment]
I converted it to tokenizer.json using convert_slow_tokenizer but got an error like that.
![Screenshot from 2023-12-05 17-46-42](https://github.com/ufal/whisper_streaming/assets/39182360/7d0c34ee-8cd9-4864-b110-c3936bd0cd96)

![Screenshot from 2023-12-05 17-49-37](https://github.com/ufal/whisper_streaming/assets/39182360/c24f016b-8f05-47a8-a762-2445f16e4e2e)

**Comment by Gldkslfmsd** [comment]
Sorry, I don't know. But I thnik that a recent version of faster-whisper was not working with a model that I downloaded from HuggingFace long ago. Did you try to reinstall it?

**Comment by Gldkslfmsd** [comment]
btw., please rather copy paste text than post screenshots. It's better visible and searchable. You can put it to triple ticks so it's formated as code.  

```
like this
```

**Comment by kenaii** [comment]
If we use faster-whisper in the backend, it takes the **tokenizer.json** file from our model-located directory. If there isn't a tokenizer.json file in our directory, it defaults to using the one from **openai/whisper-tiny.en**, as specified in [](https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/transcribe.py), right?

If so, I want to pass my own **tokenizer.json**, but I currently only have a Hugging Face-formatted tokenizer. Do I need to convert it to **tokenizer.json**? Actually, my tokenizer works well when using the **transformers WhisperTokenizer**.

**Comment by kenaii** [comment]
Yes, I fine-tuned the Whisper model for my language. **whisper_online** works well if it doesn't contain any tokenizer, but the result is not as we wanted, as shown below. Therefore, I believe I have to use my own tokenizer, just like when I trained the Whisper model.

```
## last processed 10.54 s, now is 11.09, the latency is 0.55
11091.6247 0 7720  loseiny бол fem�ushing option том heavy�uel zero простоring birth fold tom
```

**Comment by kenaii** [comment]
Also, I tried injecting the custom lines into your **process_iter** function. It works well, but our result only displays the print statement.

   ```
 def process_iter(self):
        """Runs on the current audio buffer.
        Returns: a tuple (beg_timestamp, end_timestamp, "text"), or (None, None, "").
        The non-emty text is confirmed (committed) partial transcript.
        """

        prompt, non_prompt = self.prompt()
        '''
        print("PROMPT:", prompt, file=self.logfile)
        print("CONTEXT:", non_prompt, file=self.logfile)
        print(
            f"transcribing {len(self.audio_buffer) / self.SAMPLING_RATE:2.2f} seconds from {self.buffer_time_offset:2.2f}",
            file=self.logfile)
        '''
        res = self.asr.transcribe(self.audio_buffer, init_prompt=prompt)
        #print("TEST:", res, file=self.logfile)
        # transform to [(beg,end,"word1"), ...]

        tokenizer = WhisperTokenizer.from_pretrained('whisper_model_ct',
                                                     language="Mongolian",

                                                     task="transcribe")
        print("TS:", res, file=self.logfile)
        if len(res) > 0:
            segment = res[0]
            tokens_list = segment.tokens
            text = ""
            for token_id in tokens_list:
                text += tokenizer.decode(token_id)
            print(text, file=self.logfile)
```

**Comment by Gldkslfmsd** [comment]
I'm closing it because it is an issue of your extension code, and because of inactivity. Good luck!
