### ISSUE TITLE
It seems like opus-fast-mosestokenizer is not supported in windows

### ISSUE THREAD

**Issue by white1-doggy** [ufal/whisper_streaming#41]
![image](https://github.com/ufal/whisper_streaming/assets/76698816/d4d4b148-2969-460e-b750-0a2c39ebbcb3)
https://pypi.org/project/opus-fast-mosestokenizer/#files
there is no .whl for win

**Comment by white1-doggy** [comment]
or can you please tell me one substitution for opus-fast-mosestokenizer

**Comment by Gldkslfmsd** [comment]
this is a duplicite issue #20 .
And there's temporary fix linked in #22
