### ISSUE TITLE
Using VAD

### ISSUE THREAD

**Issue by donaldos** [ufal/whisper_streaming#43]
I'm having trouble using VAD.
To use VAD, I set the setting to True and ran the server module. 
The error "numpy.core.multiarray failed to import" occurred when the numpy version was low, so I upgraded the version and solved this problem.

However, the following error occurred during the speech recognition process: "onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(double)) , expected: (tensor(float))"

Since it seems to be an issue with the development environment, I'm sharing the following development environment.

virtual environment : conda
python : 3.8.5
numpy : 1.23.5
torch.__version__ : 1.12.1+cu113

Shoud I install tensor...?
I need your advice.

**Comment by Gldkslfmsd** [comment]
Hi,
I'm sorry, I don't know how to help. Can you specify which backend do you use? Whisper_timestamped or faster-whisper? Are you sure you installed them correctly? Can you run Whisper in offline mode with VAD using only their code? If not, you can ask their authors for help. If yes, it should work.

**Comment by donaldos** [comment]
Thank you for your response.
I used faster-whisper, If args.vad=false, the speech recognition result is obtained well in the case of file recognition. However, if you set arg.vad=true, the above error occurs.

"onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(double)) , expected: (tensor(float))"

"onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(double)) , expected: (tensor(float))"

Based on the above error... it seems to be a data type issue, especially in numpy related functions.

Thanks for your help.

**Comment by donaldos** [comment]
Dear...
I solved this problem.
The reason is the python numpy version and librosa library. etc....
Thank you.

**Comment by koiking213** [comment]
@donaldos 
I have the same problem now.
Could you share the specific versions of numpy and librosa?

**Comment by Gldkslfmsd** [comment]
Great. Can you please share the fix? Either copy paste the change as  a comment, or make PR. 
Others may benefit from it.

**Comment by henriklied** [comment]
I'm still getting this error even after pulling the latest changes. Any ideas for another workaround that might work?

**Comment by Gldkslfmsd** [comment]
Hi, @henriklied . Can you check your librosa version, and maybe try the latest? Maybe it depends on it?

Or, can you give minimum reproducible example? Short audiofile, setup, dependencies versions, ...
