### ISSUE TITLE
youtube m3u8 use whisper streaming?

### ISSUE THREAD

**Issue by Arcelibs** [ufal/whisper_streaming#47]
Hello, I am currently making a software for youtube live real-time translation
It is known that I can use yt-dlp to obtain the .m3u8 file of youtube streaming audio only

How do I use whisper_streaming to concatenate m3u8?

**Comment by Gldkslfmsd** [comment]
Hi, sorry, I don't know. Maybe convert to wav and then concatenate?

Anyway, this code accepts only one audio format, the conversions should be resolved elsewhere. I can't maintain them, there are so many of them.
