### ISSUE TITLE
Enable translate to any language

### ISSUE THREAD

**Issue by prajdabre** [ufal/whisper_streaming#5]
Recently this hack was discovered to make whisper translate from X speech to Y text: https://github.com/Vaibhavs10/translate-with-whisper

Enabling this in whisper\_streaming would be good.

**Comment by 201806071216** [comment]
good good  !

**Comment by 201806071216** [comment]
I don't know if you're dealing with the form of the stream   What is the data type of a variable, can you help me?

**Comment by Gldkslfmsd** [comment]
sorry, we can't. This is not related question to this issue and you don't give sufficient details

**Comment by Gldkslfmsd** [comment]
so, I read README of  https://github.com/Vaibhavs10/translate-with-whisper , and it looks very simply: use audio in X language, and set Whisper as transcribe in Y language. This is already available in the current implementation of Whisper-Streaming. But I noticed that this zero-shot translation performance is rather small. It could be improved by tuning the parameters :

              "penalty_alpha": 0.6, 
              "top_k": 5,
