### ISSUE TITLE
Any Idea for feature update for targeted speaker transcription?

### ISSUE THREAD

**Issue by Jeevi10** [ufal/whisper_streaming#53]

**Comment by Gldkslfmsd** [comment]
hi, what do you mean by "targeted speaker transcription"?
I think that if you use an underlying model that supports it, instead of the default Whisper, than it will work.

**Comment by Jeevi10** [comment]
I mean, suppose multiple speakers speak in an environment ( noisy environment where people are speaking in the background) 
I would like to transcribe the main speaker (who is close to mic) only, I tested the "mic_test_whisper_simple.py" it works very well, however it tend to capture all the noises ( still speech but far from mic) in-between my speech.
