### ISSUE TITLE
speech can not be handled after some silence for a while or some different languages

### ISSUE THREAD

**Issue by weiyshay** [ufal/whisper_streaming#54]
Hi,
Thanks a lot for your project, I am trying to test it.

Overall it works well if it is consecutive speech while sometime the server stops any output after silence for a while or a different language. I am suspecting it is some limitation in split words.

Is there any option to recover it or reset it manually? Thanks!

**Comment by Gldkslfmsd** [comment]
Hi, can you give info for reproducibility? What language, what model, what min-chunk-size, do you use VAD?

It might be expected behavior. When two consecutive updates do not agree on a prefix, then it takes a long time to. 
Someone in #39 suggested Voice Activity controller that would commit right after 500 seconds of silence. I implemented it in a [branch](https://github.com/ufal/whisper_streaming/tree/vad-streaming). It works fine but it's not yet finished to be merged to master.

**Comment by weiyshay** [comment]
Thank you for your quick response!

I tried Japnese, Chinese and English, in case starting from any of them and then mixed with 
another for several minutes and back to the original, the output is like some

**Comment by weiyshay** [comment]
Lost some transcripts using the vad branch:
```
32870 33550  コンタクトを取れ
33990 39190 テンサー作動せよ もうやってますよ地域 異常なし
39690 40430 放射能
40830 41550  検知センス
41690 68030 どうしたのかしら立花教授の息子さんだねこちら古生団体の時子何人目なの
169580 170100 ミサイル
170100 171480 だろって誰が誰を打ったって
171480 171720 言うんだ
```

**Comment by Gldkslfmsd** [comment]
When you use `--lan en`, it expects that you speak English. Whisper is multi-lingual and robust and sometimes works on the "wrong" language, but it's an undocumented feature.

**Comment by weiyshay** [comment]
thanks for your comments, when I was transcribing a  'wav' file, it spent some time to detect the language until I give the '--lan' option. I will try no-lang option on stream.

BTW, whisper also supports translate, while it only output the translated text.
Is there an option to get both the original and the target languages like google translate?

**Comment by Gldkslfmsd** [comment]
> thanks for your comments, when I was transcribing a 'wav' file, it spent some time to detect the language until I give the '--lan' option. I will try no-lang option on stream.

Speech language ID is not currently implemented in Whisper-Streaming, unlike in the offline Whisper.


> Is there an option to get both the original and the target languages like google translate?

you can use two parallel instances of Whisper-Streaming. Batching for 2 outputs at once is currently not supported.
