### ISSUE TITLE
Usage as Fronteend+Backend app with websockets

### ISSUE THREAD

**Issue by AmgadHasan** [ufal/whisper_streaming#6]
Hi. 

Thank you so much for this great product.

I want to build a product that does real time transcription. It will consist of two parts:
1- A lightweight front end app (android app or a simple web ui) that records the audio and sends it to a server
2- A server that uses whisper to do real time transcription and return the results.

My question is how can I do this using whisper streaming. Should I use websocket to connect the frontend with the backend? What should be the length of the audio chunk that will be sent one at a time.

I hope you can help me with this.

Thanks

**Comment by Gldkslfmsd** [comment]
hi, 
thanks for your interest.

Server is already implemented -- see [whisper_online_server.py](https://github.com/ufal/whisper_streaming/blob/main/whisper_online_server.py) and **Server** section in README. There's a simple TCP socket implemented.

Audio chunk size has an impact on latency and quality. I recommend e.g. 0.5 or 1 second. Expect that the minimum latency will be at least twice more for English ASR, rather more. See the pre-print paper for details.

**Comment by Gldkslfmsd** [comment]
anyway, audio chunk size in TCP packet is arbitrary, except too large extreme. Because --min-chunk-size parameter overrides it.

**Comment by Gldkslfmsd** [comment]
please, reopen if you have a follow up question. Thank you!
