### ISSUE TITLE
Incremental delay on live transcriptions

### ISSUE THREAD

**Issue by J-Korn** [ufal/whisper_streaming#63]
I am attempting to use whisper_streaming to transcribe a live stream
I ffmpeg the stream to get just the audio and send it to the whisper socket port
It starts off working great with the transcriptions appearing immediately, but as it goes on it gets slower and slower.
I tried setting the initial prompt to "" on each iteration but it made no difference

**Comment by J-Korn** [comment]
I am piping the output of ffmpeg from an rtmp stream to the proper port:
ffmpeg -i {stream_url} -acodec pcm_s16le -ar 16000 -ac 1 -f s16le - | nc localhost 43001
the language is Greek
I am also seeing delays in some cases where the transcript will hang and then output a large sentence, even with lower values in the following if:
if len(self.audio_buffer)/self.SAMPLING_RATE > 2:
            # ...on the last completed segment (labeled by Whisper)
            self.chunk_completed_segment(res)
for example

commenting  self.chunk_completed_segment(res) and uncommenting the  # alternative: on any word block also seems to make little to no difference

**Comment by Gldkslfmsd** [comment]
> if len(self.audio_buffer)/self.SAMPLING_RATE > 2:
> # ...on the last completed segment (labeled by Whisper)
> self.chunk_completed_segment(res)

can you specify this place in code? 

You can also inspect that the audio is not lagging between pipes or within ffmpeg. Save it to file and then simulate with whisper_online.py.

**Comment by J-Korn** [comment]
# if the audio buffer is longer than 30s, trim it...
        if len(self.audio_buffer)/self.SAMPLING_RATE > 30:
            # ...on the last completed segment (labeled by Whisper)
            self.chunk_completed_segment(res)

            # alternative: on any word
            #l = self.buffer_time_offset + len(self.audio_buffer)/self.SAMPLING_RATE - 10
            # let's find commited word that is less
            #k = len(self.commited)-1
            #while k>0 and self.commited[k][1] > l:
            #    k -= 1
            #t = self.commited[k][1] 
            print(f"chunking because of len",file=self.logfile)
            #self.chunk_at(t)

It's in def process_iter(self) in whisper_online.py

**Comment by Gldkslfmsd** [comment]
>  the transcript will hang and then output a large sentence

This is expected behaviour with LocalAgreement streaming policy. Two subsequent updates must agree on a prefix to output it, otherwise they wait for the next updates, so the delay is larger.

**Comment by J-Korn** [comment]
> Are you using the most recent version of whisper_online.py? It's different now
I was not aware there was a newer version. Can I see somewhere what has changed?

> Are you trying the large model?
Large model was too slow for my needs so I'm using medium

> Using plain OpenAI Whisper I am getting ~40minutes of Greek video transcribed in ~10 minutes, using large model

**Comment by Gldkslfmsd** [comment]
> > Are you using the most recent version of whisper_online.py? It's different now
> 
> I was not aware there was a newer version. Can I see somewhere what has changed?

history of commits, version diff, ... 
Standard git features.

> 
> > Are you trying the large model?
> 
> Large model was too slow for my needs so I'm using medium

We noticed that for Czech, other models than medium are so bad quality that they are practically unusable.

Are you using faster-whisper backend and GPU? That one is the fastest.
 
> > If it's bad in offline mode, it can't be better in online
> 
> Using plain OpenAI Whisper I am getting ~40minutes of Greek video transcribed in ~10 minutes, using large model

OK. You can also use shorter test.

**Comment by Gldkslfmsd** [comment]
@J-Korn , please re-open if you have follow up question or issue

**Comment by J-Korn** [comment]
@Gldkslfmsd I have updated to the new version, indeed it's working better than before and it does a great job for short duration streams or when the speakers talk in short sentences.
However, in longer streams, or when someone talks fast, or sometimes if speaker 1 talks for a while then speaker 2 starts talking, I am seeing a delay in output longer than the set buffer_trimming_sec.
It prints out "not enough segments to chunk" in chunk_completed_segment

We need to find a way to avoid long outputs and instead have more frequent, shorter transcripts

model: large-v2
backend: faster-whisper
min-chunk-size: 1.0
language: el
buffer_trimming_sec: 5

**Comment by Gldkslfmsd** [comment]
> longer than the set buffer_trimming_sec

there's no guarantee for maximum waiting time.  buffer_trimming_sec is not a limit for this.
Unlimited waiting is an expected feature, it gives the best quality-latency trade off as far as we know. You can implement e.g. Wait-K strategy and compare it to current one. If there's an empirical evidence, we can change it.

> We need to find a way to avoid long outputs and instead have more frequent, shorter transcripts

there's Voice Activity Controller in vad-streaming branch = finish and commit on 500ms silence. The feature works but code is not finished yet.
