### ISSUE TITLE
arecord on Windows

### ISSUE THREAD

**Issue by happywch** [ufal/whisper_streaming#64]
arecord is generally used under Linux. I would like to know what tools you use under Windows.

**Comment by Gldkslfmsd** [comment]
hi, I don't use Windows, you need to ask elsewhere. I googled ffmpeg and sox

**Comment by lex6i** [comment]
I mananged successfully using sox and ncat on windows, my command looks like this
`rec -c 1 -r 16000 -t raw - | ncat localhost 43007`

**Comment by jeffxiaofu** [comment]
> 我在 Windows 上成功使用 sox 和 ncat 进行管理，我的命令如下所示 `rec -c 1 -r 16000 -t raw - | ncat localhost 43007`

What is rec?

**Comment by lex6i** [comment]
It’s a part of sox

**Comment by jeff-getlucky** [comment]
> It’s a part of sox

Only MacOS support rec

**Comment by lex6i** [comment]
Thats not true, as stated in my original comment I am using windows

**Comment by abdullahkhalid00** [comment]
> Thats not true, as stated in my original comment I am using windows



> I mananged successfully using sox and ncat on windows, my command looks like this `rec -c 1 -r 16000 -t raw - | ncat localhost 43007`

I installed both `sox` and `ncat` on windows but I still get the following error whenever I try to run the above command. Can you explain your process of installation? Maybe I'm missing something.

```
> rec -c 1 -r 16000 -t raw - | ncat localhost 43007
'rec' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by schmich** [comment]
Newer versions of sox, at least as of version 14.4.2, no longer ships with `rec.exe`. Instead, all functionality has been rolled into `sox.exe`

I was able to get this working on Windows 10 with:

`sox -t waveaudio -d -t raw -c 1 -r 16000 - | ncat localhost 43007`
`python whisper_online_server.py --host localhost --port 43007`
