### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by MartsinovichDanya** [ufal/whisper_streaming#67]
![изображение](https://github.com/ufal/whisper_streaming/assets/29692521/c7ed6c19-9b24-44c7-badb-7cf7dc116456)
I try to call whisper-online.py with downloaded model, model loads normaly, but after that I get Segmentation fault. Has anyone faced this problem or got any ideas what it could be?
I have cuda 12.2 ; faster-whisper==0.10.0 ; torch==2.1.1 ; opus-fast-mosestokenizer==0.0.8.5
Also does anyone know how to get more detailed error?

**Comment by Gldkslfmsd** [comment]
hi,
I'm not sure but maybe I got it because of OOM. You can breakpoint what causes it. 
And maybe you can try the original faster-whisper client. If it works and runs, this should as well. Or a shorter audio, if this one is very long.

**Comment by Gldkslfmsd** [comment]
please reopen if you have follow up comments
