### ISSUE TITLE
[BUG] AttributeError: 'MosesTokenizer' object has no attribute 'split'

### ISSUE THREAD

**Issue by AmgadHasan** [ufal/whisper_streaming#7]
Hello again. 

I managed to run the server. However, I got this error when I was translating foreign audio into English:

```
  File "/home/eng_amghasan/whisper_streaming/whisper_online_server.py", line 215, in <module>
    proc.process()
  File "/home/eng_amghasan/whisper_streaming/whisper_online_server.py", line 186, in process
    o = online.process_iter()
  File "/home/eng_amghasan/whisper_streaming/whisper_online.py", line 276, in process_iter
    self.chunk_completed_sentence()
  File "/home/eng_amghasan/whisper_streaming/whisper_online.py", line 322, in chunk_completed_sentence
    sents = self.words_to_sentences(self.commited)
  File "/home/eng_amghasan/whisper_streaming/whisper_online.py", line 376, in words_to_sentences
    s = self.tokenizer.split(t)
AttributeError: 'MosesTokenizer' object has no attribute 'split'
whisper-server-INFO: killing process 138718
```

**Comment by AmgadHasan** [comment]
> hello,
> 
> have you installed the intended version? `pip install opus-fast-mosestokenizer`

Yeah it works! Thanks
Maybe it's a good idea to create a requirements.txt file that contains librosa + the right version of moses tokenizer?
I'll open a pr.

**Comment by lucasjinreal** [comment]
has anyone able to install `opus-fast-mosestokenizer` on macOS?

**Comment by jonigl** [comment]
Hey everyone! I’ve created a fork to address the issues with running the project on Apple Silicon-based machines: https://github.com/jonigl/whisper_streaming_apple_silicon_fix

I simply added the suggestions shared here to make it easier to run on M1/M2/etc Macs . I’ve also updated the `README.md` with step-by-step instructions to make testing super simple on MacOS.

Hopefully, this helps anyone who's had trouble getting it to work! Feel free to check it out and let me know if you have any feedback
