### ISSUE TITLE
About LocalAgreement

### ISSUE THREAD

**Issue by rookie0607** [ufal/whisper_streaming#73]
Hello developers, I would like to ask about LocalAgreement, which piece of code he embodied in this project? Best wishes.

**Comment by Gldkslfmsd** [comment]
hi,
it's here: https://github.com/ufal/whisper_streaming/blob/3aee2fb709abf514ae5c6e02213fda8a86cb46e5/whisper_online.py#L275C1-L297C22

It compares self.buffer and self.new
