### ISSUE TITLE
Link about the research paper seem broken

### ISSUE THREAD

**Issue by jpoutrin** [ufal/whisper_streaming#74]
Hello, 
just to let you know the link seem broken.

Link: https://www.afnlp.org/conferences/ijcnlp2023/proceedings/main-demo/cdrom/pdf/2023.ijcnlp-demo.3.pdf

Result: 

<img width="837" alt="Screenshot 2024-03-28 at 17 29 55" src="https://github.com/ufal/whisper_streaming/assets/129433/e57ed8e5-a9b0-4b59-8a09-c66eca905ecb">

**Comment by Gldkslfmsd** [comment]
Thanks! Let's link the ACL Anthology.

**Comment by Gldkslfmsd** [comment]
done
