### ISSUE TITLE
TypeError: Translations.create() got an unexpected keyword argument 'timestamp_granularities'

### ISSUE THREAD

**Issue by muhammed-enes-koroglu** [ufal/whisper_streaming#79]
Hi, firstly, thank you for this amazing project. 

However, I have been unable to get the program running. I've tried faster-whisper first as my backend, but i kept getting some weird `.dll not found` errors which I could not find a solution to. 

Then I uninstalled faster-whisper and installed openai using pip and manually added an environment key OPENAI_API_KEY = "sk-xxx" (xxx being the rest of my key). When i tried running, this raised an error that the api key was not defined and that I should add it to the environment or provide one in the code. Which seems weird to me, but ok. I provided one in the function call to openai and the error disappeared. 

I then ran `python whisper_online_server.py --host localhost --port 8089 --model large-v3 --backend openai-api`, which immediately spun up the server. When I tried to go to `localhost:8089`, it showed on the console that there was a connection. However, even after waiting for minutes, I didn't get a website on the browser. I have tried this on multiple browsers, so I know the issue is not due to a specific browser.

Upon closing the tab, I get the following error on the console: 
`transcript = proc.create(**params)
^^^^^^^^^^^^^^^^^^^^^
TypeError: Translations.create() got an unexpected keyword argument 'timestamp_granularities'`

After getting this error, I wanted locate where the problem laid: on the server or on the transcription software. So I ran the following command much to the same effect: `python whisper_online.py audio.mp3 --model large-v3 --backend openai-api --offline`

What am i doing wrong? Am I missing something? 

Thank you in advance for your help!

Kind regards

**Comment by Gldkslfmsd** [comment]
hi,

> However, even after waiting for minutes, I didn't get a website on the browser. I have tried this on multiple browsers, so I know the issue is not due to a specific browser.

there's no website. It's a TCP server, the client should send audio. You can use netcat as a client. Read the documentation in README.

**Comment by Gldkslfmsd** [comment]
> However, I have been unable to get the program running. I've tried faster-whisper first as my backend, but i kept getting some weird `.dll not found` errors which I could not find a solution to.

Do you want to specify it, give reproducible details? Maybe you missed the LD_LIBRARY_PATH? https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#install-with-pip-linux-only

Feel free to reopen if you want to continue.
