### ISSUE TITLE
`tgt_language undefined` problem on `main`

### ISSUE THREAD

**Issue by regularfry** [ufal/whisper_streaming#83]
Looks like there's been a bad merge at some point, or something.  This code is [currently](https://github.com/ufal/whisper_streaming/blob/782d281badca3105843d23e2d1ef9756346b2423/whisper_online_server.py#L33) in `whisper_online_server.py`:

```python
tokenizer = create_tokenizer(tgt_language)
```

But the definition of `tgt_language` has been moved into [`asr_factory()`](https://github.com/ufal/whisper_streaming/blob/782d281badca3105843d23e2d1ef9756346b2423/whisper_online.py#L582) in `whisper_online.py`, so that breaks the server startup.

It's a simple fix, and I've done it in #80 [here](https://github.com/ufal/whisper_streaming/pull/80/commits/ebdde208f3efb1232f7c5ab2421944d5c3e4ec54#diff-7990080b3b7cc1479f1dfb7c5de7b02b16684f515b4e82e3672a64c6e7aeecdeL43) but it might want pulling out to its own patch.

**Comment by Gldkslfmsd** [comment]
I'm lost, I hope it's fixed when I merged #80.

**Comment by regularfry** [comment]
Looks like it. If I search for `tgt_language` I only find it in the `asr_factory` function so that should be fixed now.
