### ISSUE TITLE
Can't run from windows the command of recording from mic

### ISSUE THREAD

**Issue by Mina2209** [ufal/whisper_streaming#84]
I need the equivalent of this command for windows, I am frustrated from trying and getting errors.
arecord -f S16_LE -c1 -r 16000 -t raw -D default | nc localhost 43001

**Comment by lex6i** [comment]
I had success on windowes using sox and ncat, my command is
`rec -c 1 -r 16000 -t raw - | ncat localhost 43007`

**Comment by SpicyRicecaker** [comment]
@mercurial-moon I installed `sox` using the `scoop` package manager and it seemed to add `rec` to path for me. Would like to note that the `--host` and `--port` flags seem to not have any effect on windows, but sticking with the default port `43007` as suggested in the command by @lex6i works pretty well.

Also if you get a `FAIL sox: Sorry, there is no default audio device configured` for rec, for some reason adding the AUDIODRIVER ="waveaudio" environment variable seems to fix it (https://superuser.com/questions/1768655/sox-on-windows-11-no-default-audio-device-configured).
