### ISSUE TITLE
Tracking down delay

### ISSUE THREAD

**Issue by J-Korn** [ufal/whisper_streaming#85]
Hello again Dominik,
I am seeing roughly a 10 second interval between the given stream and the output.
I'm trying to track it down by adding some logging at the point where the audio is received and when the transcription is generated.
My issue is with keeping track of what segment is processed at what point, so I can say, for example, "Segment 1 received at 12:35:27, output given at 12:35:38", "Segment 2 received at..." etc

Could you give me a couple of pointers on how to achieve this?

**Comment by Gldkslfmsd** [comment]
hi, 
see the debug prints:

```
DEBUG	## last processed 10.01 s, now is 10.70, the latency is 0.69
```

I hope you can read in the code what "the latency" is in this context. You can also suggest rewriting the debug prints so that it's easier to understand.

**Comment by Gldkslfmsd** [comment]
so was this info enough? Feel free to reopen.
Good luck!
