### ISSUE TITLE
[BUG] Unnecessary socket re-creation inside with statement in whisper_online_server.py

### ISSUE THREAD

**Issue by DoiiarX** [ufal/whisper_streaming#90]
Is this re-creation of the socket intended for a specific reason, or is it an oversight that needs fixing? I would like to contribute by addressing this issue if it is indeed unintended.

## Description
In the `whisper_online_server.py` file, there is an unnecessary re-creation of a socket object inside a `with` statement which can potentially lead to resource leakage. The existing code snippet is:

```python
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
```

## Issue
The socket `s` is being recreated inside the `with` statement, which overrides the original socket created by the `with` statement itself. This not only defeats the purpose of the `with` statement which is supposed to handle the creation and destruction of the socket but also potentially leaks the original socket since it's not properly closed.

## Expected Behavior
The socket should be created once and managed by the `with` statement to ensure proper resource management without leaks. The code should simply be:

```python
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    # Use socket `s` here
```

## Steps to Reproduce
This is a static code issue and can be observed directly by reviewing the code in `whisper_online_server.py`.

## Possible Solution
Remove the line that unnecessarily recreates the socket inside the `with` statement.

Thank you for addressing this issue.

**Comment by Gldkslfmsd** [comment]
Thanks! It's an oversight.
Have you tested your PR? If yes and it works, I'll mege it.

**Comment by DoiiarX** [comment]
> Thanks! It's an oversight. Have you tested your PR? If yes and it works, I'll merge it.

yes. no problem.

**Comment by Gldkslfmsd** [comment]
thanks!
