### ISSUE TITLE
Use of another backend

### ISSUE THREAD

**Issue by NessrineTrabelsi** [ufal/whisper_streaming#92]
Is it possible to use another backend? as Wizper (fai.ai), or other whisper providers (besides OpenAI)?

**Comment by Gldkslfmsd** [comment]
hi, so far we integrated OpenAI API. I suppose it is possible to host the same API elsewhere, and only change the parameters, or calling function. It should be simple, if you do it, send a PR if the others can benefit from it.
Thanks!

**Comment by Gldkslfmsd** [comment]
please reopen if there is any update.
Good luck!
