### ISSUE TITLE
OpenAi Api not adding punctuation

### ISSUE THREAD

**Issue by abnerf** [ufal/whisper_streaming#93]
Hi everyone,

I have been using this project, but for some reason the same setup returns punctuated transcripts when using Faster Whisper (any model), but not when I use the OpenAI API.

Any ideas why that may be happening?

Thanks!

**Comment by Gldkslfmsd** [comment]
same setup - have you tried the computationally unaware mode in both? with the large model?

**Comment by marcinmatys** [comment]
Hello

The project is very interesting and I wanted to test it starts with using openai-api ,
but I have the same problem with punctuation.

I tests transcription using this instruction
`python whisper_online.py --backend openai-api file.mp3 --language pl --min-chunk-size 3 --model large > out.txt`

I don't have any punctuation. 
When I send the same audio directly to openai api, I have all punctuations dots comas and others.

I have tested also --offline option, the same problem.

Does this problem only occur for openai-api ? How we can solve this ?
I haven't tested faster-whisper yet.
Is there no problem with punctuation when using faster-whisper? 
What could be the reason for this discrepancy?

**Comment by abnerf** [comment]
> same setup - have you tried the computationally unaware mode in both? with the large model?

Not sure what you mean. Do you have a command that I could give it a try?

**Comment by abnerf** [comment]
> Hello
> 
> The project is very interesting and I wanted to test it starts with using openai-api , but I have the same problem with punctuation.
> 
> I tests transcription using this instruction `python whisper_online.py --backend openai-api file.mp3 --language pl --min-chunk-size 3 --model large > out.txt`
> 
> I don't have any punctuation. When I send the same audio directly to openai api, I have all punctuations dots comas and others.
> 
> I have tested also --offline option, the same problem.
> 
> Does this problem only occur for openai-api ? How we can solve this ? I haven't tested faster-whisper yet. Is there no problem with punctuation when using faster-whisper? What could be the reason for this discrepancy?

When I used faster whisper I got the punctuation just fine on my side, but I was trying with english though.

**Comment by Gldkslfmsd** [comment]
> > same setup - have you tried the computationally unaware mode in both? with the large model?
> 
> Not sure what you mean. Do you have a command that I could give it a try?

`whisper_online.py --comp_unaware`

**Comment by abnerf** [comment]
> > > same setup - have you tried the computationally unaware mode in both? with the large model?
> > 
> > 
> > Not sure what you mean. Do you have a command that I could give it a try?
> 
> `whisper_online.py --comp_unaware`

Thanks for the suggestion, but it didn't work for me.

**Comment by Gldkslfmsd** [comment]
what do you mean by "didn't work"? Did you get identical results from faster-whisper and openai using the same comp. unaware chunk size and the model that's inside openai?

**Comment by Gldkslfmsd** [comment]
so, if you have a reproducible evidence that that faster-whisper and openaiapi give different results, then feel free to reopen

**Comment by marcinmatys** [comment]
I can give an evidence, based on 30 seconds recording in polish language.
[download audio file](https://drive.google.com/file/d/1v2GoNigqV6M3FJHuQmBljvZ_4v49i1vK/view?usp=sharing)
Below two call, first using openai-api and result without punctuation and second using faster-whisper and result with punctuation.

python whisper_online.py --backend openai-api recording2.wav --language pl  --offline > out.txt  
result: Kobiety doświadczają dużej presji by spełnić idea perfekcyjnej matki który często jest nierealistyczny W przestrzeni publicznej spotykają się z informacjami że macierzyństwo to wyłącznie źródło nieustającego szczęścia a trudności związane z dobrostanem psychicznym są jedynie efektem ubocznym zmian hormonalnych i wkrótce same ustąpią Co więcej ich stan niejednokrotnie bagatelizuje w najbliższe im osoby To zjawisko często prowadzi do izolacji i samotności u młodych mam

python whisper_online.py --backend faster-whisper recording2.wav --language pl --model large-v2 --offline > out2.txt   
result:  Kobiety doświadczają dużej presji, by spełnić idea perfekcyjnej matki, który często jest nierealistyczny. W przestrzeni publicznej spotykają się z informacjami, że macierzyństwo to wyłącznie źródło nieustającego szczęścia, a trudności związane z dobrostanem psychicznym są jedynie efektem ubocznym zmian hormonalnych i wkrótce same ustąpią. Co więcej, ich stan niejednokrotnie bagatelizuje w najbliższe im osoby. To zjawisko często prowadzi do izolacji i samotności u młodych mam.

**Comment by marcinmatys** [comment]
@abnerf please reopen issue.
I am not reporter and probably thats why I can't.

**Comment by Denis-Kazakov** [comment]
It is true that OpenAI can produce time-stamped words but without punctuation. What I did I used jiwer.process_words to align sentences (with punctuation but without timestamps) with time-stamped words.
