### ISSUE TITLE
OpenAI Whisper is not working anymore as a backend for whisper_streaming

### ISSUE THREAD

**Issue by parth-singh71** [ufal/whisper_streaming#94]
[OpenAI Whisper API](https://platform.openai.com/docs/api-reference/audio/verbose-json-object) response has been updated and it no longer gives the "words" key in the response due to which whisper_streaming fails to run.

Please let me know if you are planing to update the code for new API responses and if yes by when can we expect this release?

Thanks in advance

**Comment by Gldkslfmsd** [comment]
the link you send has "Verbose Json" section where the word timestamps are included.

**Comment by Gldkslfmsd** [comment]
no plan ahead. PR is welcome.
Thanks!

**Comment by parth-singh71** [comment]
https://github.com/ufal/whisper_streaming/issues/94#issuecomment-2142751355

> the link you send has "Verbose Json" section where the word timestamps are included.

Yes I have tried that, it does not work.
Just try running that API via openai module and you won't get "words" key anymore, you will get "tokens" key instead which is basically the word embeddings of the words used.

**Comment by marcinmatys** [comment]
> [#94 (comment)](https://github.com/ufal/whisper_streaming/issues/94#issuecomment-2142751355)
> 
> > the link you send has "Verbose Json" section where the word timestamps are included.
> 
> Yes I have tried that, it does not work. Just try running that API via openai module and you won't get "words" key anymore, you will get "tokens" key instead which is basically the word embeddings of the words used.

To get words we need 
response_format="verbose_json",
timestamp_granularities=["word"]

**Comment by parth-singh71** [comment]
`timestamp_granularities` is only available for transcription API, what about translation API?

I am using `whisper_streaming` for translation task.

**Comment by parth-singh71** [comment]
> > [#94 (comment)](https://github.com/ufal/whisper_streaming/issues/94#issuecomment-2142751355)
> > > the link you send has "Verbose Json" section where the word timestamps are included.
> > 
> > 
> > Yes I have tried that, it does not work. Just try running that API via openai module and you won't get "words" key anymore, you will get "tokens" key instead which is basically the word embeddings of the words used.
> 
> To get words we need response_format="verbose_json", timestamp_granularities=["word"]

`timestamp_granularities` is only available for transcription API, what about translation API?

I am using `whisper_streaming` for translation task.

**Comment by kennette21** [comment]
I also just encountered the `timestamp_granularities` issue with translation. I am also not clear how to set target language for translation. Is it always translating back to English as the target language?

**Comment by Gldkslfmsd** [comment]
yes, to English. Sometimes to other lang but it's an undocumented feature
and is low quality.

Thomas Bean ***@***.***> schrieb am So. 14. 7. 2024 um 05:24:

**Comment by promet99** [comment]
#137 will solve this problem. @parth-singh71 @Gldkslfmsd
