### ISSUE TITLE
unexpected slow speed

### ISSUE THREAD

**Issue by tuantuanzhang** [ufal/whisper_streaming#96]
I test python whisper_online.py example2.mp3 --language en --min-chunk-size 1  --model large-v2  > out.txt
and find its latency is large....
`Note: Illegal Audio-MPEG-Header 0x36312c31 at offset 96960.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
INFO    Audio duration is: 2.42 seconds
INFO    Loading Whisper large-v2 model for en...
INFO    done. It took 4.72 seconds.
DEBUG   PROMPT: 
DEBUG   CONTEXT: 
DEBUG   transcribing 1.00 seconds from 0.00
DEBUG   >>>>COMPLETE NOW: (None, None, '')
DEBUG   INCOMPLETE: (None, None, '')
DEBUG   len of buffer now: 1.00
DEBUG   ## last processed 1.00 s, now is 5.14, the latency is 4.14
DEBUG   PROMPT: 
DEBUG   CONTEXT: 
DEBUG   transcribing 2.42 seconds from 0.00
DEBUG   >>>>COMPLETE NOW: (None, None, '')
DEBUG   INCOMPLETE: (0.0, 2.4, ' Do I take care of wood wound?')
DEBUG   len of buffer now: 2.42
DEBUG   ## last processed 5.14 s, now is 13.40, the latency is 8.26
DEBUG   last, noncommited: (0.0, 2.4, ' Do I take care of wood wound?')
13397.2638 0 2400  Do I take care of wood wound?`

**Comment by Gldkslfmsd** [comment]
hi, is it translation or transcription?
what HW do you use?

**Comment by Gldkslfmsd** [comment]
feel free to reopen if you continue

**Comment by tuantuanzhang** [comment]
A100



| |
xinrongnuaa
|
|
***@***.***
|




---- Replied Message ----
| From | Dominik ***@***.***> |
| Date | 06/05/2024 14:35 |
| To | ***@***.***> |
| Cc | Xinrong ***@***.***>、State ***@***.***> |
| Subject | Re: [ufal/whisper_streaming] unexpected slow speed (Issue #96) |

hi, is it translation or transcription?
what HW do you use?
