### ISSUE TITLE
bilgi/ instructions notice learning

### ISSUE THREAD

**Issue by yenerismail** [ufal/whisper_streaming#99]
Son kullanıcı olarak, (Yazılım bilgim bulunmamaktadır.)
Model değişimini nasıl yapabiliriz.? Seçenek belirtme olabilir mi?
Win işletim sisteminde, gerçek zamanlı olarak, mikrofondan gelen sesi nasıl yazıya dökebiliriz.?
(Win11, Gpu RTX4090, NPU, Bellek:96Gb)
Sağır olduğum için, gerçek zamanlı benim için önem taşımaktadır.

Google translate,
As an end user, (I have no software knowledge.)
How can we change the model? Is it possible to specify an option?
How can we transcribe the sound coming from the microphone in real time in the Win operating system?
(Win11, GPU RTX4090, NPU, Memory: 96Gb)
Since I'm deaf, real time is important to me.

\AppData\Local\Programs\Python\Python310\whisper_streaming>python whisper_online_server.py
INFO    Loading Whisper large-v2 model for auto...
INFO    done. It took 6.22 seconds.
WARNING Whisper is not warmed up. The first chunk processing may take longer.
INFO    Listening on('localhost', 43007)
INFO    Connected to client on ('127.0.0.1', 58827)      wait...............  There are no results

**Comment by Gldkslfmsd** [comment]
hi, see README.md. It's answered fhere.
Don't you miss client or the input for the server?

**Comment by Gldkslfmsd** [comment]
audio input from mic on windows is not documemted. I hope you find answer elsewhere
